# Generated by Django 3.2 on 2021-04-22 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=64)),
                ('institute', models.CharField(max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('preffered_subject', models.TextField()),
                ('preffered_medium', models.CharField(max_length=64)),
                ('preffered_class', models.TextField()),
                ('preffered_time', models.TextField()),
                ('address_covered', models.TextField()),
                ('address_division', models.CharField(max_length=64)),
                ('address_district', models.CharField(max_length=64)),
                ('address_present', models.TextField()),
                ('address_phone', models.TextField()),
                ('expected_salary', models.IntegerField()),
                ('tution_status', models.BooleanField(default=True)),
                ('working_days', models.IntegerField()),
                ('place_of_learning', models.CharField(max_length=64)),
                ('extra_facilities', models.TextField()),
                ('current_tution_number', models.IntegerField(default=0)),
                ('total_tution_so_far', models.IntegerField(default=0)),
                ('ssc_exam_year', models.IntegerField(default=None)),
                ('ssc_institute', models.CharField(max_length=100)),
                ('ssc_subject', models.CharField(max_length=64)),
                ('ssc_result', models.CharField(max_length=25)),
                ('hsc_exam_year', models.IntegerField()),
                ('hsc_institute', models.CharField(max_length=100)),
                ('hsc_subject', models.CharField(max_length=64)),
                ('hsc_result', models.CharField(max_length=25)),
                ('honours_exam_year', models.IntegerField()),
                ('honours_institute', models.CharField(max_length=100)),
                ('honours_subject', models.CharField(max_length=64)),
                ('honours_result', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('address_division', models.CharField(max_length=64)),
                ('address_district', models.CharField(max_length=64)),
                ('address_present', models.TextField()),
                ('address_phone', models.TextField()),
                ('info_class', models.CharField(max_length=64)),
                ('info_medium', models.CharField(max_length=64)),
                ('info_gender', models.CharField(max_length=10)),
                ('institute', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
