# Generated by Django 3.2 on 2021-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tutor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='profile/default.png', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(default='profile/default.png', upload_to='profile'),
        ),
    ]
