# Generated by Django 3.2 on 2021-04-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tutor_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField()),
                ('time_confirmed', models.DateTimeField(blank=True)),
                ('time_ended', models.DateTimeField(blank=True)),
                ('rating_given', models.IntegerField(blank=True)),
                ('salary', models.IntegerField()),
                ('student_class', models.CharField(max_length=64)),
                ('student_medium', models.CharField(max_length=64)),
                ('student_subjects', models.CharField(max_length=100)),
                ('student_location', models.CharField(max_length=512)),
                ('student_gender', models.CharField(max_length=10)),
                ('requirement_gender', models.CharField(max_length=10)),
                ('requirement_teaching_time', models.CharField(max_length=64)),
                ('requirement_days_per_week', models.IntegerField()),
                ('requirement_others', models.CharField(max_length=512)),
                ('confirmed', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('tutor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutionRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tution')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tutor')),
            ],
        ),
    ]
