# Generated by Django 3.2 on 2021-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tution_tutionrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tution',
            name='rating_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tution',
            name='time_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tution',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
