# Generated by Django 3.2 on 2021-04-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210426_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tution',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tutor'),
        ),
    ]
