# Generated by Django 3.2 on 2021-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tution_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='student_number',
            field=models.IntegerField(default=1),
        ),
    ]
