# Generated by Django 3.2 on 2021-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tution_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='student_district',
            field=models.CharField(default='Dhaka', max_length=64),
            preserve_default=False,
        ),
    ]
